import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeMode from "./shared/components/ThemeMode";
import CardNav from "@/app/shared/components/CardNav";
import logo from "../public/Trackify_logo.png";
import { items } from "@/app/shared/data/Items";
import { Profile } from "./shared/components/Profile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tracking Products",
  description: "Generated by Gustavo Lima",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeMode />
        {children}
        <Profile name="Gustavo Lima" className="mt-3.5 w-12 h-12" />
        <CardNav 
          logo={logo}
          logoAlt="Company Logo"
          items={items}
          baseColor="#fff"
          menuColor="#000"
          buttonBgColor="#111"
          buttonTextColor="#fff"
          ease="power3.out"
        />
      </body>
    </html>
  );
}
